# Site settings
title: Rosarito Centro
email: contactp@rosaritocentro.com
description: >- 
  Tu mejor opción en Desarrollo Web, Marketing Digital y Diseño Gráfico.
baseurl: ""
url: "https://rosaritocentro.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-130293099-3
lang: es_mx

minima:
  date_format: "%-d de %B del %Y"
  # generate social links in footer
  # social_links:
  #   twitter: jekyllrb

social:
  name: Rosarito Centro
  links:
    - https://www.facebook.com/RosaritoCentroBC/
    - https://www.instagram.com/rosaritocentro/
    - https://twitter.com/CentroRosarito
    - https://www.linkedin.com/in/rosaritocentro/

# Build settings
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package-lock.json
  - package.json
  - gulpfile.js
  - img-temp/
  
collections:
  directorio:
    output: true
  servicios:
    output: true
 
defaults:
  -
    scope:
      path: ""
    values:
      lang: "es"
      lazy: true
      image:
        path: og-img.png
        height: 
        width: 
