# Site settings
title: Rosarito Centro
email: your-email@example.com
description: >- 
  Rosarito Centro, el mejor sitio de Playas de Rosarito
baseurl: ""
url: "https://rosaritocentro.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: denicolasromero
google_analytics: UA-130293099-3
lang: es_mx

minima:
  date_format: "%-d de %B del %Y"
  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss


# Build settings
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package-lock.json
  - package.json
  - gulpfile.js
  - img-temp/
  
collections:
  directorio:
    output: true
  servicios:
    output: true
 
defaults:
  -
    scope:
      path: ""
    values:
      lang: "es"
      lazy: true
      image:
        path: /assets/img/rosaritocentro/rosarito.jpg
        height: 5000
        width: 3705